### ISSUE TITLE
Unable to leave lobby because of CSync v2

### ISSUE THREAD

**Issue by LoafOrc** [Gaibryol/SuperiorSelling#1]
CSync updated to 2.0.0 which has broken your mod completely. They've provided a tutorial here: https://thunderstore.io/c/lethal-company/p/Owen3H/CSync/wiki/1681-updating-to-v200/ on how to update to 2.0.0 effectively.

**Comment by Gaibryol** [comment]
Thanks for the heads up! I'll update it very soon.
